# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd7"

  config.vm.synced_folder "../build", "/nebula"

  # config.vm.provision "shell", inline: <<-EOD
  #   sudo kldload if_tap
  # EOD
end
