name: gofmt
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/gofmt.yml'
      - '**.go'
jobs:

  gofmt:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
        check-latest: true

    - name: Install goimports
      run: |
        go install golang.org/x/tools/cmd/goimports@latest

    - name: gofmt
      run: |
        if [ "$(find . -iname '*.go' | grep -v '\.pb\.go$' | xargs goimports -l)" ]
        then
          find . -iname '*.go' | grep -v '\.pb\.go$' | xargs goimports -d
          exit 1
        fi
