name: smoke
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/smoke**'
      - '**Makefile'
      - '**.go'
      - '**.proto'
      - 'go.mod'
      - 'go.sum'
jobs:

  smoke:
    name: Run multi node smoke test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go1.19-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go1.19-

    - name: build
      run: make bin-docker

    - name: setup docker image
      working-directory: ./.github/workflows/smoke
      run: ./build.sh

    - name: run smoke
      working-directory: ./.github/workflows/smoke
      run: ./smoke.sh

    - name: setup relay docker image
      working-directory: ./.github/workflows/smoke
      run: ./build-relay.sh

    - name: run smoke relay
      working-directory: ./.github/workflows/smoke
      run: ./smoke-relay.sh

    timeout-minutes: 10
